version: '3.1'

services:
  server:
    container_name: vh-server
    hostname: vh-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - GO_VER=${GO_VER}
        - ALPINE_VER=${ALPINE_VER}
        - APP_NAME=${SERVER_APP_NAME}
    env_file:
      - ./.env
    environment:
      - DB_HOSTNAME=vh-db
    networks:
      - vh-internal-network
      - vh-external-network
    ports:
      - "${HTTP_SERVER_LISTEN_PORT}:${HTTP_SERVER_LISTEN_PORT}"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: vh-db
    hostname: vh-db
    restart: unless-stopped
    image: postgres:${POSTGRES_VER}-alpine${ALPINE_VER}
    environment:
      - PGDATA=/data
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ${DB_LOCAL_DIR}:/data
    networks:
      - vh-internal-network
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  vh-internal-network:
    name: vh-internal-network
    driver: bridge
    internal: true

  vh-external-network:
    name: vh-external-network
    driver: bridge
    internal: false
